title:          BSA Troop 65 Astoria
tagline:        The power to change the world lives in your actions.
url:            http://www.t65q.org
paginate:       10
theme: 		jekyll-theme-cayman

author:
  name:         Aaron Helton
  url:          http://aaron.heltonfamily.info
  email:        ah@heltonfamily.info

collections:
  news:
    output: true
    paginate: 10
  events:
    output: true
    paginate: 10

gems:
  - jekyll-sitemap

